import {expect} from 'chai'

import {createConfigDir, removeConfigDir, runCli, runCliJson, runCliOk} from './helpers.js'

type Row = Record<string, unknown>
type WriteResult = {data: {result: {affectedRows: number}}; success: boolean}

// Each test owns a uniquely named scratch table so the suite is re-runnable
// against a long-lived container and safe to run alongside other spec files.
const scratch = (suffix: string) => `scratch_${suffix}_${process.pid}`

describe('e2e: safety rules and writes', () => {
  let configDir: string
  const created: string[] = []

  before(async () => {
    configDir = await createConfigDir()
  })

  after(async () => {
    for (const table of created) {
      // eslint-disable-next-line no-await-in-loop
      await runCli(['psql', 'query', `DROP TABLE IF EXISTS ${table}`, '--skip-confirmation'], configDir)
    }

    await removeConfigDir(configDir)
  })

  async function createScratch(suffix: string): Promise<string> {
    const table = scratch(suffix)
    created.push(table)
    await runCliOk(
      [
        'psql',
        'query',
        `CREATE TABLE ${table} (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, note varchar(64) NOT NULL)`,
      ],
      configDir,
    )
    return table
  }

  it('blocks a blacklisted operation outright', async () => {
    const {code, stderr} = await runCli(['psql', 'query', 'DROP DATABASE pg_e2e_alt'], configDir)

    expect(code).to.not.equal(0)
    expect(stderr).to.include('"DROP DATABASE" is blacklisted')
    expect(stderr).to.include('blocked by safety rules')

    // The database must still be there.
    const payload = await runCliJson<{data: {databases: string[]}}>(['psql', 'databases'], configDir)
    expect(payload.data.databases).to.include('pg_e2e_alt')
  })

  it('blocks a blacklisted operation written with extra whitespace', async () => {
    const {code, stderr} = await runCli(['psql', 'query', 'DROP  DATABASE pg_e2e_alt'], configDir)

    expect(code).to.not.equal(0)
    expect(stderr).to.include('"DROP DATABASE" is blacklisted')

    const payload = await runCliJson<{data: {databases: string[]}}>(['psql', 'databases'], configDir)
    expect(payload.data.databases).to.include('pg_e2e_alt')
  })

  it('blocks a blacklisted operation separated by a comment', async () => {
    // PostgreSQL accepts a comment wherever whitespace is legal, so the guard
    // has to see through it — otherwise this really does drop the database.
    const {code, stderr} = await runCli(
      ['psql', 'query', 'DROP/* sneaky */DATABASE pg_e2e_alt', '--skip-confirmation'],
      configDir,
    )

    expect(code).to.not.equal(0)
    expect(stderr).to.include('"DROP DATABASE" is blacklisted')

    const payload = await runCliJson<{data: {databases: string[]}}>(['psql', 'databases'], configDir)
    expect(payload.data.databases).to.include('pg_e2e_alt')
  })

  it('blocks a blacklisted operation split across lines', async () => {
    const {code, stderr} = await runCli(
      ['psql', 'query', 'DROP\n  DATABASE pg_e2e_alt', '--skip-confirmation'],
      configDir,
    )

    expect(code).to.not.equal(0)
    expect(stderr).to.include('"DROP DATABASE" is blacklisted')

    const payload = await runCliJson<{data: {databases: string[]}}>(['psql', 'databases'], configDir)
    expect(payload.data.databases).to.include('pg_e2e_alt')
  })

  it('requires confirmation when a leading comment pushes the operation onto its own line', async () => {
    // Runs against a scratch table: if the guard ever regresses, the DELETE
    // executes, and it must not be able to touch the seeded fixtures.
    const table = await createScratch('comment')
    await runCliOk(['psql', 'query', `INSERT INTO ${table} (note) VALUES ('keep me')`], configDir)

    const {code, stdout} = await runCli(['psql', 'query', `/* migration 12 */\nDELETE FROM ${table}`], configDir)

    expect(code).to.equal(0)
    expect(stdout).to.include('This query contains a destructive operation: DELETE')

    const check = await runCliJson<{data: {result: Row[]}}>(
      ['psql', 'query', `SELECT COUNT(*)::int AS c FROM ${table}`],
      configDir,
    )
    expect(check.data.result[0].c).to.equal(1)
  })

  it('requires confirmation for a destructive statement hidden behind a SELECT', async () => {
    // Already caught today by the legacy substring fallback (` DELETE ` has a
    // space on both sides here) — kept so the rewrite cannot regress it.
    const table = await createScratch('second')
    await runCliOk(['psql', 'query', `INSERT INTO ${table} (note) VALUES ('keep me')`], configDir)

    const {code, stdout} = await runCli(['psql', 'query', `SELECT 1; DELETE FROM ${table}`], configDir)

    expect(code).to.equal(0)
    expect(stdout).to.include('This query contains a destructive operation: DELETE')

    const check = await runCliJson<{data: {result: Row[]}}>(
      ['psql', 'query', `SELECT COUNT(*)::int AS c FROM ${table}`],
      configDir,
    )
    expect(check.data.result[0].c).to.equal(1)
  })

  it('requires confirmation for a destructive statement hidden behind a SELECT with no space after the semicolon', async () => {
    // No space after the ';' — the legacy ` DELETE ` substring fallback misses
    // this shape today, so the driver runs both statements and the row is
    // really deleted.
    const table = await createScratch('nospace')
    await runCliOk(['psql', 'query', `INSERT INTO ${table} (note) VALUES ('keep me')`], configDir)

    const {code, stdout} = await runCli(['psql', 'query', `SELECT 1;DELETE FROM ${table}`], configDir)

    expect(code).to.equal(0)
    expect(stdout).to.include('This query contains a destructive operation: DELETE')

    const check = await runCliJson<{data: {result: Row[]}}>(
      ['psql', 'query', `SELECT COUNT(*)::int AS c FROM ${table}`],
      configDir,
    )
    expect(check.data.result[0].c).to.equal(1)
  })

  it('does not demand confirmation for a SELECT whose data merely says "delete"', async () => {
    const payload = await runCliJson<{data: {result: Row[]}; success: boolean}>(
      ['psql', 'query', "SELECT 'please delete me' AS note"],
      configDir,
    )

    expect(payload.success).to.be.true
    expect(payload.data.result).to.deep.equal([{note: 'please delete me'}])
  })

  it('refuses a destructive query without --skip-confirmation and changes nothing', async () => {
    const {code, stdout} = await runCli(['psql', 'query', 'DELETE FROM orders WHERE id = 1'], configDir)

    expect(code).to.equal(0)
    expect(stdout).to.include('This query contains a destructive operation: DELETE')
    expect(stdout).to.include('Re-run with --skip-confirmation to proceed.')

    const check = await runCliJson<{data: {result: Row[]}}>(
      ['psql', 'query', 'SELECT COUNT(*)::int AS c FROM orders WHERE id = 1'],
      configDir,
    )
    expect(check.data.result[0].c).to.equal(1)
  })

  it('runs INSERT, UPDATE and DELETE against a scratch table', async () => {
    const table = await createScratch('crud')

    const inserted = await runCliJson<WriteResult>(
      ['psql', 'query', `INSERT INTO ${table} (note) VALUES ('alpha'), ('beta')`],
      configDir,
    )
    expect(inserted.data.result.affectedRows).to.equal(2)

    const updated = await runCliJson<WriteResult>(
      ['psql', 'query', `UPDATE ${table} SET note = 'gamma' WHERE note = 'alpha'`, '--skip-confirmation'],
      configDir,
    )
    expect(updated.data.result.affectedRows).to.equal(1)

    const selected = await runCliJson<{data: {result: Row[]}}>(
      ['psql', 'query', `SELECT note FROM ${table} ORDER BY id`],
      configDir,
    )
    expect(selected.data.result).to.deep.equal([{note: 'gamma'}, {note: 'beta'}])

    const deleted = await runCliJson<WriteResult>(
      ['psql', 'query', `DELETE FROM ${table} WHERE note = 'beta'`, '--skip-confirmation'],
      configDir,
    )
    expect(deleted.data.result.affectedRows).to.equal(1)

    const remaining = await runCliJson<{data: {result: Row[]}}>(
      ['psql', 'query', `SELECT COUNT(*)::int AS c FROM ${table}`],
      configDir,
    )
    expect(remaining.data.result[0].c).to.equal(1)
  })

  it('warns about an UPDATE with no WHERE clause but still runs it', async () => {
    // The table name contains "where", which must not read as a WHERE clause.
    const table = await createScratch('nowhere')
    await runCliOk(['psql', 'query', `INSERT INTO ${table} (note) VALUES ('a'), ('b')`], configDir)

    const {stderr, stdout} = await runCliOk(
      ['psql', 'query', `UPDATE ${table} SET note = 'wiped'`, '--skip-confirmation'],
      configDir,
    )

    expect(stdout + stderr).to.include('Missing WHERE clause in UPDATE/DELETE query')
    expect(stdout + stderr).to.include('Affected rows: 2')
  })

  it('creates and drops a table through the CLI', async () => {
    const table = await createScratch('lifecycle')

    const afterCreate = await runCliJson<{data: {tables: string[]}}>(['psql', 'tables'], configDir)
    expect(afterCreate.data.tables).to.include(table)

    await runCliOk(['psql', 'query', `DROP TABLE ${table}`, '--skip-confirmation'], configDir)

    const afterDrop = await runCliJson<{data: {tables: string[]}}>(['psql', 'tables'], configDir)
    expect(afterDrop.data.tables).to.not.include(table)
  })

  it('survives many CLI invocations hitting the server at once', async () => {
    // Each invocation is its own process with its own pool, so this exercises
    // connection setup/teardown under parallel load rather than the in-process
    // query-slot queue (which only ever sees one query per CLI run).
    const results = await Promise.all(
      Array.from({length: 8}, async (_, i) =>
        runCliJson<{data: {result: Row[]}}>(
          ['psql', 'query', `SELECT pg_sleep(0.2) IS NULL AS slept, ${i} AS n`],
          configDir,
        ),
      ),
    )

    // A run that exits 0 without actually executing the query would still
    // pass an exit-code-only check, so also confirm each invocation got back
    // the exact row it asked for.
    for (const [i, payload] of results.entries()) {
      // pg_sleep() returns void, and `void IS NULL` is false — the check
      // exists only to force the driver to wait, not to assert a value.
      expect(payload.data.result[0]).to.deep.equal({n: i, slept: false})
    }
  })

  it('exits promptly after a query, leaving no connection open', async () => {
    const countConnections = async (): Promise<number> => {
      const payload = await runCliJson<{data: {result: Row[]}}>(
        ['psql', 'query', "SELECT COUNT(*)::int AS c FROM pg_stat_activity WHERE datname = 'pg_e2e'"],
        configDir,
      )
      return Number(payload.data.result[0].c)
    }

    // Baseline is read via its own CLI invocation, whose connection is closed
    // by the time it returns, so it reflects steady-state activity before the
    // query under test runs.
    const baseline = await countConnections()

    const started = Date.now()
    await runCliOk(['psql', 'query', 'SELECT 1 AS one'], configDir)
    const elapsed = Date.now() - started

    // A leaked pool would keep the event loop alive well past what one
    // SELECT 1 needs; 20s was generous enough to pass even on a full hang.
    expect(elapsed).to.be.lessThan(5000)

    // A leaked connection from the query above would still show up here, so
    // this must not have grown relative to the baseline.
    expect(await countConnections()).to.be.at.most(baseline)
  })
})
